import React, { useState, useEffect } from 'react';
import { 
  BarChart3, 
  TrendingUp, 
  TrendingDown, 
  Users, 
  Clock, 
  Target,
  Calendar,
  Zap,
  Download
} from 'lucide-react';
import jsPDF from 'jspdf';
import { 
  LineChart, 
  Line, 
  AreaChart, 
  Area, 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer, 
  PieChart, 
  Pie, 
  Cell,
  Legend
} from 'recharts';
import axios from 'axios';
import toast from 'react-hot-toast';

const Analytics = () => {
  const [analyticsData, setAnalyticsData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [timeRange, setTimeRange] = useState('7d');

  useEffect(() => {
    fetchAnalyticsData();
  }, [timeRange]);

  const fetchAnalyticsData = async () => {
    try {
      const response = await axios.get('/api/analytics/dashboard');
      setAnalyticsData(response.data);
    } catch (error) {
      // Fallback data when backend is not available
      setAnalyticsData({
        performance: {
          completion_rate: 75,
          avg_completion_time: 3.2,
          productivity_score: 8.5
        },
        trends: [
          { date: '2024-01-01', tasks: 12, completed: 8 },
          { date: '2024-01-02', tasks: 15, completed: 11 },
          { date: '2024-01-03', tasks: 18, completed: 14 },
          { date: '2024-01-04', tasks: 14, completed: 12 },
          { date: '2024-01-05', tasks: 16, completed: 13 }
        ],
        department_performance: [
          { department: 'IT', efficiency: 85, tasks_completed: 45 },
          { department: 'HR', efficiency: 78, tasks_completed: 32 },
          { department: 'Marketing', efficiency: 82, tasks_completed: 38 }
        ]
      });
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async () => {
    try {
      const reportData = {
        title: 'Analytics Report',
        date: new Date().toLocaleDateString(),
        performance: analyticsData?.performance || {},
        trends: analyticsData?.trends || [],
        departmentPerformance: analyticsData?.department_performance || []
      };

      // Create PDF document
      const pdf = new jsPDF();
      
      // Set up fonts and colors
      pdf.setFont('helvetica');
      
      // Header
      pdf.setFontSize(20);
      pdf.setTextColor(40, 40, 40);
      pdf.text('Global Web Work - Analytics Report', 20, 30);
      
      pdf.setFontSize(12);
      pdf.setTextColor(100, 100, 100);
      pdf.text(`Generated on: ${reportData.date}`, 20, 40);
      
      // Performance Metrics
      pdf.setFontSize(16);
      pdf.setTextColor(40, 40, 40);
      pdf.text('Performance Metrics', 20, 60);
      
      pdf.setFontSize(12);
      pdf.text(`Completion Rate: ${reportData.performance.completion_rate || 0}%`, 20, 75);
      pdf.text(`Average Completion Time: ${reportData.performance.avg_completion_time || 0} days`, 20, 85);
      pdf.text(`Productivity Score: ${reportData.performance.productivity_score || 0}/10`, 20, 95);
      
      // Department Performance
      pdf.setFontSize(16);
      pdf.text('Department Performance', 20, 115);
      
      pdf.setFontSize(12);
      let yPos = 130;
      reportData.departmentPerformance.forEach(dept => {
        pdf.text(`${dept.department}: ${dept.efficiency}% efficiency, ${dept.tasks_completed} tasks completed`, 20, yPos);
        yPos += 10;
      });
      
      // Footer
      pdf.setFontSize(10);
      pdf.setTextColor(150, 150, 150);
      pdf.text('Generated by Global Web Work AI-Powered Task Management System', 20, 280);
      
      // Download the PDF
      pdf.save(`analytics-report-${new Date().toISOString().split('T')[0]}.pdf`);
      
      toast.success('Analytics report downloaded successfully!');
    } catch (error) {
      console.error('Download error:', error);
      toast.error('Failed to download analytics report');
    }
  };

  // Mock data for demonstration
  const productivityData = [
    { day: 'Mon', completed: 12, created: 8, overdue: 2 },
    { day: 'Tue', completed: 18, created: 12, overdue: 1 },
    { day: 'Wed', completed: 15, created: 10, overdue: 3 },
    { day: 'Thu', completed: 22, created: 15, overdue: 1 },
    { day: 'Fri', completed: 20, created: 18, overdue: 2 },
    { day: 'Sat', completed: 8, created: 5, overdue: 0 },
    { day: 'Sun', completed: 5, created: 3, overdue: 1 }
  ];

  const teamPerformanceData = [
    { name: 'John Doe', completed: 45, pending: 8, efficiency: 85 },
    { name: 'Jane Smith', completed: 38, pending: 12, efficiency: 76 },
    { name: 'Mike Johnson', completed: 52, pending: 5, efficiency: 91 },
    { name: 'Sarah Wilson', completed: 41, pending: 9, efficiency: 82 },
    { name: 'David Brown', completed: 33, pending: 15, efficiency: 69 }
  ];

  const priorityTrendData = [
    { month: 'Jan', high: 12, medium: 25, low: 18 },
    { month: 'Feb', high: 15, medium: 28, low: 22 },
    { month: 'Mar', high: 18, medium: 32, low: 25 },
    { month: 'Apr', high: 14, medium: 30, low: 28 },
    { month: 'May', high: 16, medium: 35, low: 30 },
    { month: 'Jun', high: 20, medium: 38, low: 32 }
  ];

  const departmentData = analyticsData?.department_stats ? 
    Object.entries(analyticsData.department_stats).map(([dept, stats]) => ({
      department: dept,
      total: stats.total,
      completed: stats.completed,
      pending: stats.total - stats.completed,
      completionRate: Math.round((stats.completed / stats.total) * 100) || 0
    })) : [];

  const priorityData = analyticsData?.priority_distribution ? [
    { name: 'High Priority', value: analyticsData.priority_distribution.high, color: '#ef4444' },
    { name: 'Medium Priority', value: analyticsData.priority_distribution.medium, color: '#f59e0b' },
    { name: 'Low Priority', value: analyticsData.priority_distribution.low, color: '#10b981' }
  ] : [];

  const COLORS = ['#ef4444', '#f59e0b', '#10b981'];

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="spinner w-8 h-8"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
            Analytics
          </h1>
          <p className="text-gray-600 dark:text-gray-400 mt-1">
            AI-powered insights and performance metrics
          </p>
        </div>
        <div className="flex items-center space-x-4">
          <button
            onClick={handleDownload}
            className="flex items-center px-3 py-1.5 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors text-sm"
          >
            <Download className="w-4 h-4 mr-1.5" />
            Download
          </button>
          <select
            value={timeRange}
            onChange={(e) => setTimeRange(e.target.value)}
            className="form-input"
          >
            <option value="7d">Last 7 days</option>
            <option value="30d">Last 30 days</option>
            <option value="90d">Last 90 days</option>
            <option value="1y">Last year</option>
          </select>
          <div className="flex items-center space-x-2">
            <Zap className="w-5 h-5 text-yellow-500" />
            <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
              AI Insights
            </span>
          </div>
        </div>
      </div>

      {/* Key Metrics */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="card">
          <div className="flex items-center">
            <div className="p-3 rounded-lg bg-blue-100 dark:bg-blue-900">
              <Target className="w-6 h-6 text-blue-600 dark:text-blue-400" />
            </div>
            <div className="ml-4">
              <p className="text-sm font-medium text-gray-600 dark:text-gray-400">
                Total Tasks
              </p>
              <p className="text-2xl font-bold text-gray-900 dark:text-white">
                {analyticsData?.overview?.total_tasks || 0}
              </p>
              <p className="text-xs text-green-600 dark:text-green-400 flex items-center">
                <TrendingUp className="w-3 h-3 mr-1" />
                +12% from last week
              </p>
            </div>
          </div>
        </div>

        <div className="card">
          <div className="flex items-center">
            <div className="p-3 rounded-lg bg-green-100 dark:bg-green-900">
              <TrendingUp className="w-6 h-6 text-green-600 dark:text-green-400" />
            </div>
            <div className="ml-4">
              <p className="text-sm font-medium text-gray-600 dark:text-gray-400">
                Completion Rate
              </p>
              <p className="text-2xl font-bold text-gray-900 dark:text-white">
                {analyticsData?.overview?.total_tasks ? 
                  Math.round((analyticsData.overview.completed_tasks / analyticsData.overview.total_tasks) * 100) : 0}%
              </p>
              <p className="text-xs text-green-600 dark:text-green-400 flex items-center">
                <TrendingUp className="w-3 h-3 mr-1" />
                +5% from last week
              </p>
            </div>
          </div>
        </div>

        <div className="card">
          <div className="flex items-center">
            <div className="p-3 rounded-lg bg-yellow-100 dark:bg-yellow-900">
              <Clock className="w-6 h-6 text-yellow-600 dark:text-yellow-400" />
            </div>
            <div className="ml-4">
              <p className="text-sm font-medium text-gray-600 dark:text-gray-400">
                Avg. Completion Time
              </p>
              <p className="text-2xl font-bold text-gray-900 dark:text-white">
                2.3 days
              </p>
              <p className="text-xs text-red-600 dark:text-red-400 flex items-center">
                <TrendingDown className="w-3 h-3 mr-1" />
                -0.5 days from last week
              </p>
            </div>
          </div>
        </div>

        <div className="card">
          <div className="flex items-center">
            <div className="p-3 rounded-lg bg-purple-100 dark:bg-purple-900">
              <Users className="w-6 h-6 text-purple-600 dark:text-purple-400" />
            </div>
            <div className="ml-4">
              <p className="text-sm font-medium text-gray-600 dark:text-gray-400">
                Active Users
              </p>
              <p className="text-2xl font-bold text-gray-900 dark:text-white">
                24
              </p>
              <p className="text-xs text-green-600 dark:text-green-400 flex items-center">
                <TrendingUp className="w-3 h-3 mr-1" />
                +3 from last week
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Charts Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Productivity Trend */}
        <div className="card">
          <div className="card-header">
            <h3 className="card-title">Productivity Trend</h3>
            <p className="card-subtitle">Tasks completed vs created over time</p>
          </div>
          <div className="h-80">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={productivityData}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="day" />
                <YAxis />
                <Tooltip />
                <Legend />
                <Area 
                  type="monotone" 
                  dataKey="completed" 
                  stackId="1" 
                  stroke="#10b981" 
                  fill="#10b981" 
                  fillOpacity={0.6}
                />
                <Area 
                  type="monotone" 
                  dataKey="created" 
                  stackId="2" 
                  stroke="#3b82f6" 
                  fill="#3b82f6" 
                  fillOpacity={0.6}
                />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Priority Distribution */}
        <div className="card">
          <div className="card-header">
            <h3 className="card-title">Priority Distribution</h3>
            <p className="card-subtitle">Current task priorities</p>
          </div>
          <div className="h-80">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={priorityData}
                  cx="50%"
                  cy="50%"
                  innerRadius={60}
                  outerRadius={100}
                  paddingAngle={5}
                  dataKey="value"
                >
                  {priorityData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip />
                <Legend />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Department Performance */}
      <div className="card">
        <div className="card-header">
          <h3 className="card-title">Department Performance</h3>
          <p className="card-subtitle">Task completion rates by department</p>
        </div>
        <div className="h-80">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={departmentData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="department" />
              <YAxis />
              <Tooltip />
              <Legend />
              <Bar dataKey="completed" fill="#10b981" name="Completed" />
              <Bar dataKey="pending" fill="#f59e0b" name="Pending" />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Team Performance */}
      <div className="card">
        <div className="card-header">
          <h3 className="card-title">Team Performance</h3>
          <p className="card-subtitle">Individual productivity metrics</p>
        </div>
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200 dark:divide-slate-700">
            <thead className="bg-gray-50 dark:bg-slate-700">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                  Team Member
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                  Completed
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                  Pending
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                  Efficiency
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                  Trend
                </th>
              </tr>
            </thead>
            <tbody className="bg-white dark:bg-slate-800 divide-y divide-gray-200 dark:divide-slate-700">
              {teamPerformanceData.map((member, index) => (
                <tr key={index}>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center">
                      <div className="w-8 h-8 bg-blue-100 dark:bg-blue-900 rounded-full flex items-center justify-center">
                        <Users className="w-4 h-4 text-blue-600 dark:text-blue-400" />
                      </div>
                      <div className="ml-3">
                        <div className="text-sm font-medium text-gray-900 dark:text-white">
                          {member.name}
                        </div>
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className="text-sm text-gray-900 dark:text-white">
                      {member.completed}
                    </span>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className="text-sm text-gray-900 dark:text-white">
                      {member.pending}
                    </span>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center">
                      <div className="w-16 bg-gray-200 dark:bg-slate-600 rounded-full h-2 mr-2">
                        <div 
                          className="bg-blue-600 h-2 rounded-full" 
                          style={{ width: `${member.efficiency}%` }}
                        ></div>
                      </div>
                      <span className="text-sm text-gray-900 dark:text-white">
                        {member.efficiency}%
                      </span>
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center">
                      {member.efficiency >= 80 ? (
                        <TrendingUp className="w-4 h-4 text-green-500" />
                      ) : member.efficiency >= 60 ? (
                        <TrendingUp className="w-4 h-4 text-yellow-500" />
                      ) : (
                        <TrendingDown className="w-4 h-4 text-red-500" />
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Priority Trends */}
      <div className="card">
        <div className="card-header">
          <h3 className="card-title">Priority Trends</h3>
          <p className="card-subtitle">Task priority distribution over time</p>
        </div>
        <div className="h-80">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={priorityTrendData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="month" />
              <YAxis />
              <Tooltip />
              <Legend />
              <Line type="monotone" dataKey="high" stroke="#ef4444" strokeWidth={2} name="High Priority" />
              <Line type="monotone" dataKey="medium" stroke="#f59e0b" strokeWidth={2} name="Medium Priority" />
              <Line type="monotone" dataKey="low" stroke="#10b981" strokeWidth={2} name="Low Priority" />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>
    </div>
  );
};

export default Analytics;
