import React, { useState, useEffect } from 'react';
import { 
  CheckSquare, 
  Clock, 
  AlertTriangle, 
  TrendingUp, 
  Users, 
  Calendar,
  Target,
  Zap,
  Download,
  Plus,
  Eye
} from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';
import { useNavigate } from 'react-router-dom';
import jsPDF from 'jspdf';
import axios from 'axios';
import toast from 'react-hot-toast';

const Dashboard = () => {
  const [dashboardData, setDashboardData] = useState(null);
  const [aiSuggestions, setAiSuggestions] = useState([]);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    fetchDashboardData();
    fetchAISuggestions();
  }, []);

  const fetchDashboardData = async () => {
    try {
      const response = await axios.get('/api/analytics/dashboard');
      setDashboardData(response.data);
    } catch (error) {
      // Fallback data when backend is not available
      setDashboardData({
        overview: {
          total_tasks: 12,
          completed_tasks: 8,
          pending_tasks: 3,
          overdue_tasks: 1
        },
        priority_distribution: {
          high: 3,
          medium: 5,
          low: 4
        },
        department_stats: {
          'IT': { total: 8, completed: 6 },
          'HR': { total: 4, completed: 2 }
        }
      });
    } finally {
      setLoading(false);
    }
  };

  const fetchAISuggestions = async () => {
    try {
      const response = await axios.get('/api/ai/suggestions');
      setAiSuggestions(response.data.suggestions);
    } catch (error) {
      // Fallback suggestions when backend is not available
      setAiSuggestions([
        {
          type: 'workload',
          message: 'You have 3 pending tasks. Consider prioritizing high-priority items.',
          priority: 'medium'
        },
        {
          type: 'deadline',
          message: '1 task is due tomorrow. Complete it today for better productivity.',
          priority: 'high'
        }
      ]);
    }
  };

  const handleDownload = async (type) => {
    try {
      const reportData = {
        title: 'Dashboard Report',
        date: new Date().toLocaleDateString(),
        stats: displayData.overview,
        priorityDistribution: displayData.priority_distribution,
        departmentStats: displayData.department_stats
      };

      // Create PDF document
      const pdf = new jsPDF();
      
      // Set up fonts and colors
      pdf.setFont('helvetica');
      
      // Header
      pdf.setFontSize(20);
      pdf.setTextColor(40, 40, 40);
      pdf.text('Global Web Work - Dashboard Report', 20, 30);
      
      pdf.setFontSize(12);
      pdf.setTextColor(100, 100, 100);
      pdf.text(`Generated on: ${reportData.date}`, 20, 40);
      
      // Overview Statistics
      pdf.setFontSize(16);
      pdf.setTextColor(40, 40, 40);
      pdf.text('Overview Statistics', 20, 60);
      
      pdf.setFontSize(12);
      pdf.text(`Total Tasks: ${reportData.stats.total_tasks}`, 20, 75);
      pdf.text(`Completed Tasks: ${reportData.stats.completed_tasks}`, 20, 85);
      pdf.text(`Pending Tasks: ${reportData.stats.pending_tasks}`, 20, 95);
      pdf.text(`Overdue Tasks: ${reportData.stats.overdue_tasks}`, 20, 105);
      
      // Priority Distribution
      pdf.setFontSize(16);
      pdf.text('Priority Distribution', 20, 125);
      
      pdf.setFontSize(12);
      pdf.text(`High Priority: ${reportData.priorityDistribution.high}`, 20, 140);
      pdf.text(`Medium Priority: ${reportData.priorityDistribution.medium}`, 20, 150);
      pdf.text(`Low Priority: ${reportData.priorityDistribution.low}`, 20, 160);
      
      // Department Performance
      pdf.setFontSize(16);
      pdf.text('Department Performance', 20, 180);
      
      pdf.setFontSize(12);
      let yPos = 195;
      Object.entries(reportData.departmentStats).forEach(([dept, stats]) => {
        const completionRate = Math.round((stats.completed / stats.total) * 100);
        pdf.text(`${dept}: ${stats.completed}/${stats.total} (${completionRate}%)`, 20, yPos);
        yPos += 10;
      });
      
      // Footer
      pdf.setFontSize(10);
      pdf.setTextColor(150, 150, 150);
      pdf.text('Generated by Global Web Work AI-Powered Task Management System', 20, 280);
      
      // Download the PDF
      pdf.save(`dashboard-report-${new Date().toISOString().split('T')[0]}.pdf`);
      
      toast.success('Dashboard report downloaded successfully!');
    } catch (error) {
      console.error('Download error:', error);
      toast.error('Failed to download dashboard report');
    }
  };

  const handleQuickAction = (action) => {
    switch (action) {
      case 'create-task':
        navigate('/tasks?action=create');
        break;
      case 'team-view':
        navigate('/tasks?view=team');
        break;
      case 'calendar':
        navigate('/calendar');
        break;
      default:
        break;
    }
  };

  // Ensure we always have data to display
  const displayData = dashboardData || {
    overview: {
      total_tasks: 0,
      completed_tasks: 0,
      pending_tasks: 0,
      overdue_tasks: 0
    },
    priority_distribution: {
      high: 0,
      medium: 0,
      low: 0
    },
    department_stats: {}
  };

  const stats = [
    {
      name: 'Total Tasks',
      value: displayData.overview.total_tasks,
      icon: CheckSquare,
      color: 'text-blue-600',
      bgColor: 'bg-blue-100 dark:bg-blue-900'
    },
    {
      name: 'Completed',
      value: displayData.overview.completed_tasks,
      icon: CheckSquare,
      color: 'text-green-600',
      bgColor: 'bg-green-100 dark:bg-green-900'
    },
    {
      name: 'Pending',
      value: displayData.overview.pending_tasks,
      icon: Clock,
      color: 'text-yellow-600',
      bgColor: 'bg-yellow-100 dark:bg-yellow-900'
    },
    {
      name: 'Overdue',
      value: displayData.overview.overdue_tasks,
      icon: AlertTriangle,
      color: 'text-red-600',
      bgColor: 'bg-red-100 dark:bg-red-900'
    }
  ];

  const priorityData = displayData.priority_distribution ? [
    { name: 'High', value: displayData.priority_distribution.high, color: '#ef4444' },
    { name: 'Medium', value: displayData.priority_distribution.medium, color: '#f59e0b' },
    { name: 'Low', value: displayData.priority_distribution.low, color: '#10b981' }
  ] : [];

  const departmentData = displayData.department_stats ? 
    Object.entries(displayData.department_stats).map(([dept, stats]) => ({
      department: dept,
      total: stats.total,
      completed: stats.completed,
      completionRate: Math.round((stats.completed / stats.total) * 100) || 0
    })) : [];

  if (loading) {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
              Dashboard
            </h1>
            <p className="text-gray-600 dark:text-gray-400 mt-1">
              Loading your dashboard...
            </p>
          </div>
        </div>
        <div className="flex items-center justify-center h-64">
          <div className="spinner w-8 h-8"></div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
            Dashboard
          </h1>
          <p className="text-gray-600 dark:text-gray-400 mt-1">
            Welcome back! Here's what's happening with your tasks.
          </p>
        </div>
        <div className="flex items-center space-x-4">
          <button
            onClick={() => handleDownload('dashboard')}
            className="flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            <Download className="w-4 h-4 mr-2" />
            Download Report
          </button>
          <div className="flex items-center space-x-2">
            <Zap className="w-5 h-5 text-yellow-500" />
            <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
              AI-Powered
            </span>
          </div>
        </div>
      </div>

      {/* AI Suggestions */}
      {aiSuggestions.length > 0 && (
        <div className="bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
          <div className="flex items-center mb-3">
            <Zap className="w-5 h-5 text-blue-600 dark:text-blue-400 mr-2" />
            <h3 className="font-semibold text-blue-900 dark:text-blue-100">
              AI Suggestions
            </h3>
          </div>
          <div className="space-y-2">
            {aiSuggestions.map((suggestion, index) => (
              <div key={index} className="flex items-start">
                <div className={`w-2 h-2 rounded-full mt-2 mr-3 ${
                  suggestion.priority === 'high' ? 'bg-red-500' : 
                  suggestion.priority === 'medium' ? 'bg-yellow-500' : 'bg-green-500'
                }`}></div>
                <p className="text-sm text-blue-800 dark:text-blue-200">
                  {suggestion.message}
                </p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {stats.map((stat, index) => {
          const Icon = stat.icon;
          return (
            <div key={index} className="card">
              <div className="flex items-center">
                <div className={`p-3 rounded-lg ${stat.bgColor}`}>
                  <Icon className={`w-6 h-6 ${stat.color}`} />
                </div>
                <div className="ml-4">
                  <p className="text-sm font-medium text-gray-600 dark:text-gray-400">
                    {stat.name}
                  </p>
                  <p className="text-2xl font-bold text-gray-900 dark:text-white">
                    {stat.value}
                  </p>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Charts Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Priority Distribution */}
        <div className="card">
          <div className="card-header">
            <h3 className="card-title">Task Priority Distribution</h3>
            <p className="card-subtitle">Current task priorities</p>
          </div>
          <div className="h-80">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={priorityData}
                  cx="50%"
                  cy="50%"
                  innerRadius={60}
                  outerRadius={100}
                  paddingAngle={5}
                  dataKey="value"
                >
                  {priorityData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Pie>
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Department Performance */}
        <div className="card">
          <div className="card-header">
            <h3 className="card-title">Department Performance</h3>
            <p className="card-subtitle">Completion rates by department</p>
          </div>
          <div className="h-80">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={departmentData}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="department" />
                <YAxis />
                <Tooltip />
                <Bar dataKey="completionRate" fill="#3b82f6" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Recent Activity */}
      <div className="card">
        <div className="card-header">
          <h3 className="card-title">Recent Activity</h3>
          <p className="card-subtitle">Latest task updates and changes</p>
        </div>
        <div className="space-y-4">
          {[
            { action: 'Task completed', task: 'Update user interface', time: '2 hours ago', user: 'John Doe' },
            { action: 'New task assigned', task: 'Review documentation', time: '4 hours ago', user: 'Jane Smith' },
            { action: 'Priority updated', task: 'Fix bug in login', time: '6 hours ago', user: 'Mike Johnson' },
            { action: 'Task created', task: 'Implement new feature', time: '8 hours ago', user: 'Sarah Wilson' }
          ].map((activity, index) => (
            <div key={index} className="flex items-center space-x-4 p-3 bg-gray-50 dark:bg-slate-700 rounded-lg">
              <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
              <div className="flex-1">
                <p className="text-sm font-medium text-gray-900 dark:text-white">
                  {activity.action}: <span className="text-blue-600 dark:text-blue-400">{activity.task}</span>
                </p>
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  {activity.time} • {activity.user}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Quick Actions */}
      <div className="card">
        <div className="card-header">
          <h3 className="card-title">Quick Actions</h3>
          <p className="card-subtitle">Common tasks and shortcuts</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <button 
            onClick={() => handleQuickAction('create-task')}
            className="flex items-center p-4 bg-blue-50 dark:bg-blue-900/20 hover:bg-blue-100 dark:hover:bg-blue-900/30 rounded-lg transition-colors cursor-pointer"
          >
            <Target className="w-6 h-6 text-blue-600 dark:text-blue-400 mr-3" />
            <div className="text-left">
              <p className="font-medium text-blue-900 dark:text-blue-100">Create Task</p>
              <p className="text-sm text-blue-700 dark:text-blue-300">Add a new task</p>
            </div>
          </button>
          
          <button 
            onClick={() => handleQuickAction('team-view')}
            className="flex items-center p-4 bg-green-50 dark:bg-green-900/20 hover:bg-green-100 dark:hover:bg-green-900/30 rounded-lg transition-colors cursor-pointer"
          >
            <Users className="w-6 h-6 text-green-600 dark:text-green-400 mr-3" />
            <div className="text-left">
              <p className="font-medium text-green-900 dark:text-green-100">Team View</p>
              <p className="text-sm text-green-700 dark:text-green-300">View team tasks</p>
            </div>
          </button>
          
          <button 
            onClick={() => handleQuickAction('calendar')}
            className="flex items-center p-4 bg-purple-50 dark:bg-purple-900/20 hover:bg-purple-100 dark:hover:bg-purple-900/30 rounded-lg transition-colors cursor-pointer"
          >
            <Calendar className="w-6 h-6 text-purple-600 dark:text-purple-400 mr-3" />
            <div className="text-left">
              <p className="font-medium text-purple-900 dark:text-purple-100">Schedule</p>
              <p className="text-sm text-purple-700 dark:text-purple-300">View calendar</p>
            </div>
          </button>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
