import React, { useState, useEffect } from 'react';
import { 
  Plus, 
  Search, 
  Filter, 
  MoreVertical, 
  Edit, 
  Trash2, 
  CheckCircle, 
  Clock,
  AlertTriangle,
  Zap,
  Calendar,
  User,
  Download
} from 'lucide-react';
import jsPDF from 'jspdf';
import axios from 'axios';
import toast from 'react-hot-toast';
import { format } from 'date-fns';

const Tasks = () => {
  const [tasks, setTasks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [selectedTask, setSelectedTask] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [filterStatus, setFilterStatus] = useState('all');
  const [filterPriority, setFilterPriority] = useState('all');
  const [newTask, setNewTask] = useState({
    title: '',
    description: '',
    assignedTo: '',
    dueDate: '',
    urgency: 5,
    complexity: 5,
    department: 'General'
  });

  useEffect(() => {
    fetchTasks();
  }, []);

  const fetchTasks = async () => {
    try {
      const response = await axios.get('/api/tasks');
      // Normalize backend task fields to a consistent shape (snake_case)
      const normalized = (response.data.tasks || []).map(t => ({
        ...t,
        due_date: t.due_date || t.dueDate || t.due || '',
        assigned_to: t.assigned_to || t.assignedTo || t.assigned || '',
        ai_priority_score: t.ai_priority_score || t.aiPriorityScore || t.ai_score || t.aiScore || ''
      }));
      setTasks(normalized);
    } catch (error) {
      // Fallback data when backend is not available
      setTasks([
        { id: '1', title: 'Design UI Mockups', description: 'Create wireframes for the new dashboard', assigned_to: 'John Doe', due_date: '2024-01-15', status: 'pending', priority: 'High', department: 'Design', ai_priority_score: '0.72' },
        { id: '2', title: 'Setup Database', description: 'Configure PostgreSQL database', assigned_to: 'Jane Smith', due_date: '2024-01-20', status: 'completed', priority: 'Medium', department: 'IT', ai_priority_score: '0.45' },
        { id: '3', title: 'Write Documentation', description: 'Document API endpoints', assigned_to: 'Mike Johnson', due_date: '2024-01-25', status: 'pending', priority: 'Low', department: 'IT', ai_priority_score: '0.30' }
      ]);
    } finally {
      setLoading(false);
    }
  };

  // Safe date formatter: returns '-' for invalid/missing dates
  const safeFormat = (dateInput, fmt) => {
    try {
      if (!dateInput) return '-';
      const d = (dateInput instanceof Date) ? dateInput : new Date(dateInput);
      if (isNaN(d.getTime())) return '-';
      return format(d, fmt);
    } catch (e) {
      return '-';
    }
  };

  const handleDownload = async () => {
    try {
      const reportData = {
        title: 'Tasks Report',
        date: new Date().toLocaleDateString(),
        tasks: tasks,
        totalTasks: tasks.length,
        completedTasks: tasks.filter(task => task.status === 'completed').length,
        pendingTasks: tasks.filter(task => task.status === 'pending').length,
        overdueTasks: tasks.filter(task => task.status === 'overdue').length
      };

      // Create PDF document
      const pdf = new jsPDF();
      
      // Set up fonts and colors
      pdf.setFont('helvetica');
      
      // Header
      pdf.setFontSize(20);
      pdf.setTextColor(40, 40, 40);
      pdf.text('Global Web Work - Tasks Report', 20, 30);
      
      pdf.setFontSize(12);
      pdf.setTextColor(100, 100, 100);
      pdf.text(`Generated on: ${reportData.date}`, 20, 40);
      
      // Task Summary
      pdf.setFontSize(16);
      pdf.setTextColor(40, 40, 40);
      pdf.text('Task Summary', 20, 60);
      
      pdf.setFontSize(12);
      pdf.text(`Total Tasks: ${reportData.totalTasks}`, 20, 75);
      pdf.text(`Completed Tasks: ${reportData.completedTasks}`, 20, 85);
      pdf.text(`Pending Tasks: ${reportData.pendingTasks}`, 20, 95);
      pdf.text(`Overdue Tasks: ${reportData.overdueTasks}`, 20, 105);
      
      // Task Details
      pdf.setFontSize(16);
      pdf.text('Task Details', 20, 125);
      
      pdf.setFontSize(10);
      let yPos = 140;
      reportData.tasks.forEach((task, index) => {
        if (yPos > 270) {
          pdf.addPage();
          yPos = 20;
        }
        pdf.text(`${index + 1}. ${task.title}`, 20, yPos);
        pdf.text(`   Assigned to: ${task.assignedTo}`, 20, yPos + 5);
        pdf.text(`   Due Date: ${task.dueDate}`, 20, yPos + 10);
        pdf.text(`   Status: ${task.status} | Priority: ${task.priority} | Department: ${task.department}`, 20, yPos + 15);
        yPos += 25;
      });
      
      // Footer
      pdf.setFontSize(10);
      pdf.setTextColor(150, 150, 150);
      pdf.text('Generated by Global Web Work AI-Powered Task Management System', 20, 280);
      
      // Download the PDF
      pdf.save(`tasks-report-${new Date().toISOString().split('T')[0]}.pdf`);
      
      toast.success('Tasks report downloaded successfully!');
    } catch (error) {
      console.error('Download error:', error);
      toast.error('Failed to download tasks report');
    }
  };

  const handleCreateTask = async (e) => {
    e.preventDefault();
    try {
      const response = await axios.post('/api/tasks', newTask);
      setTasks([...tasks, response.data.task]);
      setShowCreateModal(false);
      setNewTask({
        title: '',
        description: '',
        assignedTo: '',
        dueDate: '',
        urgency: 5,
        complexity: 5,
        department: 'General'
      });
      toast.success('Task created successfully!');
    } catch (error) {
      toast.error('Failed to create task');
    }
  };

  const handleUpdateTask = async (taskData) => {
    try {
      const response = await axios.put(`/api/tasks/${selectedTask.id}`, taskData);
      setTasks(tasks.map(task => task.id === selectedTask.id ? response.data.task : task));
      setShowEditModal(false);
      setSelectedTask(null);
      toast.success('Task updated successfully!');
    } catch (error) {
      toast.error('Failed to update task');
    }
  };

  const handleStatusChange = async (taskId, newStatus) => {
    try {
      await axios.put(`/api/tasks/${taskId}`, { status: newStatus });
      setTasks(tasks.map(task => 
        task.id === taskId ? { ...task, status: newStatus } : task
      ));
      toast.success('Task status updated!');
    } catch (error) {
      toast.error('Failed to update task status');
    }
  };

  const getPriorityColor = (priority) => {
    switch (priority) {
      case 'High': return 'text-red-600 bg-red-100 dark:bg-red-900';
      case 'Medium': return 'text-yellow-600 bg-yellow-100 dark:bg-yellow-900';
      case 'Low': return 'text-green-600 bg-green-100 dark:bg-green-900';
      default: return 'text-gray-600 bg-gray-100 dark:bg-gray-900';
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case 'completed': return 'text-green-600 bg-green-100 dark:bg-green-900';
      case 'pending': return 'text-blue-600 bg-blue-100 dark:bg-blue-900';
      case 'overdue': return 'text-red-600 bg-red-100 dark:bg-red-900';
      default: return 'text-gray-600 bg-gray-100 dark:bg-gray-900';
    }
  };

  const isOverdue = (dueDate) => {
    try {
      if (!dueDate) return false;
      const d = new Date(dueDate);
      if (isNaN(d.getTime())) return false;
      const today = new Date();
      return d < today && d.toDateString() !== today.toDateString();
    } catch (e) {
      return false;
    }
  };

  const filteredTasks = tasks.filter(task => {
    const matchesSearch = task.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
                         task.description.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesStatus = filterStatus === 'all' || task.status === filterStatus;
    const matchesPriority = filterPriority === 'all' || task.priority === filterPriority;
    return matchesSearch && matchesStatus && matchesPriority;
  });

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="spinner w-8 h-8"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
            Tasks
          </h1>
          <p className="text-gray-600 dark:text-gray-400 mt-1">
            Manage and track your tasks with AI-powered insights
          </p>
        </div>
        <div className="flex items-center space-x-4">
          <button
            onClick={handleDownload}
            className="flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            <Download className="w-4 h-4 mr-2" />
            Download Report
          </button>
          <button
            onClick={() => setShowCreateModal(true)}
            className="btn btn-primary"
          >
            <Plus className="w-5 h-5 mr-2" />
            Create Task
          </button>
        </div>
      </div>

      {/* Filters */}
      <div className="card">
        <div className="flex flex-col sm:flex-row gap-4">
          <div className="flex-1">
            <div className="input-group-left">
              <Search className="input-icon-left w-5 h-5" />
              <input
                type="text"
                placeholder="Search tasks..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="form-input"
              />
            </div>
          </div>
          <div className="flex gap-2">
            <select
              value={filterStatus}
              onChange={(e) => setFilterStatus(e.target.value)}
              className="form-input"
            >
              <option value="all">All Status</option>
              <option value="pending">Pending</option>
              <option value="completed">Completed</option>
              <option value="overdue">Overdue</option>
            </select>
            <select
              value={filterPriority}
              onChange={(e) => setFilterPriority(e.target.value)}
              className="form-input"
            >
              <option value="all">All Priority</option>
              <option value="High">High</option>
              <option value="Medium">Medium</option>
              <option value="Low">Low</option>
            </select>
          </div>
        </div>
      </div>

      {/* Tasks List */}
      <div className="space-y-4">
        {filteredTasks.length === 0 ? (
          <div className="card text-center py-12">
            <CheckCircle className="w-12 h-12 text-gray-400 mx-auto mb-4" />
            <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-2">
              No tasks found
            </h3>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              {searchQuery || filterStatus !== 'all' || filterPriority !== 'all'
                ? 'Try adjusting your filters'
                : 'Get started by creating your first task'
              }
            </p>
            {!searchQuery && filterStatus === 'all' && filterPriority === 'all' && (
              <button
                onClick={() => setShowCreateModal(true)}
                className="btn btn-primary"
              >
                <Plus className="w-5 h-5 mr-2" />
                Create Task
              </button>
            )}
          </div>
        ) : (
          filteredTasks.map((task) => (
            <div key={task.id} className="card hover:shadow-md transition-shadow">
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center space-x-3 mb-2">
                    <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                      {task.title}
                    </h3>
                    <span className={`badge ${getPriorityColor(task.priority)}`}>
                      {task.priority}
                    </span>
                    <span className={`badge ${getStatusColor(task.status)}`}>
                      {task.status}
                    </span>
                    {isOverdue(task.due_date) && (
                      <span className="badge badge-overdue">
                        <AlertTriangle className="w-3 h-3 mr-1" />
                        Overdue
                      </span>
                    )}
                  </div>
                  
                  <p className="text-gray-600 dark:text-gray-400 mb-3">
                    {task.description}
                  </p>
                  
                  <div className="flex items-center space-x-4 text-sm text-gray-500 dark:text-gray-400">
                    <div className="flex items-center">
                      <Calendar className="w-4 h-4 mr-1" />
                      Due: {safeFormat(task.due_date, 'MMM dd, yyyy')}
                    </div>
                    <div className="flex items-center">
                      <User className="w-4 h-4 mr-1" />
                      {task.assigned_to}
                    </div>
                    <div className="flex items-center">
                      <Zap className="w-4 h-4 mr-1" />
                      AI Score: {task.ai_priority_score}
                    </div>
                  </div>
                </div>
                
                <div className="flex items-center space-x-2">
                  {task.status !== 'completed' && (
                    <button
                      onClick={() => handleStatusChange(task.id, 'completed')}
                      className="btn btn-success btn-sm"
                    >
                      <CheckCircle className="w-4 h-4" />
                    </button>
                  )}
                  <button
                    onClick={() => {
                      setSelectedTask(task);
                      setShowEditModal(true);
                    }}
                    className="btn btn-secondary btn-sm"
                  >
                    <Edit className="w-4 h-4" />
                  </button>
                  <button className="btn btn-secondary btn-sm">
                    <MoreVertical className="w-4 h-4" />
                  </button>
                </div>
              </div>
            </div>
          ))
        )}
      </div>

      {/* Create Task Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-slate-800 rounded-lg max-w-md w-full max-h-[90vh] overflow-y-auto">
            <div className="p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-bold text-gray-900 dark:text-white">
                  Create New Task
                </h2>
                <button
                  onClick={() => setShowCreateModal(false)}
                  className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
                >
                  ×
                </button>
              </div>
              
              <form onSubmit={handleCreateTask} className="space-y-4">
                <div className="form-group">
                  <label className="form-label">Title *</label>
                  <input
                    type="text"
                    value={newTask.title}
                    onChange={(e) => setNewTask({...newTask, title: e.target.value})}
                    className="form-input"
                    required
                  />
                </div>
                
                <div className="form-group">
                  <label className="form-label">Description</label>
                  <textarea
                    value={newTask.description}
                    onChange={(e) => setNewTask({...newTask, description: e.target.value})}
                    className="form-input"
                    rows="3"
                  />
                </div>
                
                <div className="form-group">
                  <label className="form-label">Due Date *</label>
                  <input
                    type="date"
                    value={newTask.dueDate}
                    onChange={(e) => setNewTask({...newTask, dueDate: e.target.value})}
                    className="form-input"
                    required
                  />
                </div>
                
                <div className="grid grid-cols-2 gap-4">
                  <div className="form-group">
                    <label className="form-label">Urgency (1-10)</label>
                    <input
                      type="number"
                      min="1"
                      max="10"
                      value={newTask.urgency}
                      onChange={(e) => setNewTask({...newTask, urgency: parseInt(e.target.value)})}
                      className="form-input"
                    />
                  </div>
                  
                  <div className="form-group">
                    <label className="form-label">Complexity (1-10)</label>
                    <input
                      type="number"
                      min="1"
                      max="10"
                      value={newTask.complexity}
                      onChange={(e) => setNewTask({...newTask, complexity: parseInt(e.target.value)})}
                      className="form-input"
                    />
                  </div>
                </div>
                
                <div className="flex justify-end space-x-3">
                  <button
                    type="button"
                    onClick={() => setShowCreateModal(false)}
                    className="btn btn-secondary"
                  >
                    Cancel
                  </button>
                  <button type="submit" className="btn btn-primary">
                    Create Task
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}

      {/* Edit Task Modal */}
      {showEditModal && selectedTask && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-slate-800 rounded-lg max-w-md w-full max-h-[90vh] overflow-y-auto">
            <div className="p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-bold text-gray-900 dark:text-white">
                  Edit Task
                </h2>
                <button
                  onClick={() => setShowEditModal(false)}
                  className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
                >
                  ×
                </button>
              </div>
              
              <form onSubmit={(e) => {
                e.preventDefault();
                handleUpdateTask(selectedTask);
              }} className="space-y-4">
                <div className="form-group">
                  <label className="form-label">Title *</label>
                  <input
                    type="text"
                    value={selectedTask.title}
                    onChange={(e) => setSelectedTask({...selectedTask, title: e.target.value})}
                    className="form-input"
                    required
                  />
                </div>
                
                <div className="form-group">
                  <label className="form-label">Description</label>
                  <textarea
                    value={selectedTask.description}
                    onChange={(e) => setSelectedTask({...selectedTask, description: e.target.value})}
                    className="form-input"
                    rows="3"
                  />
                </div>
                
                <div className="form-group">
                  <label className="form-label">Status</label>
                  <select
                    value={selectedTask.status}
                    onChange={(e) => setSelectedTask({...selectedTask, status: e.target.value})}
                    className="form-input"
                  >
                    <option value="pending">Pending</option>
                    <option value="completed">Completed</option>
                    <option value="overdue">Overdue</option>
                  </select>
                </div>
                
                <div className="flex justify-end space-x-3">
                  <button
                    type="button"
                    onClick={() => setShowEditModal(false)}
                    className="btn btn-secondary"
                  >
                    Cancel
                  </button>
                  <button type="submit" className="btn btn-primary">
                    Update Task
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Tasks;
